/*
 * BilibiliLoginDialog.java
 * B站 登录对话框：使用 WebView 加载 B站 登录页面，
 * 登录完成后自动提取 Cookie 并保存到 SharedPreferences 和文件，
 * 后续 yt-dlp 使用该 Cookie 获取高画质视频流。
 */

package com.example.grayvideodl.ui.settings;

import android.app.AlertDialog;
import android.content.Context;
import android.content.SharedPreferences;
import android.os.Environment;
import android.webkit.CookieManager;
import android.webkit.WebChromeClient;
import android.webkit.WebResourceRequest;
import android.webkit.WebView;
import android.webkit.WebViewClient;

import java.io.File;
import java.io.FileOutputStream;
import java.nio.charset.StandardCharsets;

public class BilibiliLoginDialog {

    // Cookie 文件名（存于应用内部存储）
    private static final String COOKIE_FILE_NAME = "bilibili_cookies.txt";
    private static final String PREF_NAME = "grayvideodl_settings";
    private static final String KEY_BILI_LOGGED_IN = "bilibili_logged_in";

    // 回调接口
    public interface LoginCallback {
        void onLoginResult(boolean success, String message);
    }

    /*
     * show: 显示 B站 登录对话框
     * 内部使用 WebView 加载 B站 passport 登录页
     */
    public static void show(Context context, LoginCallback callback) {
        // 创建 WebView
        WebView webView = new WebView(context);
        webView.getSettings().setJavaScriptEnabled(true);
        webView.getSettings().setDomStorageEnabled(true);
        webView.getSettings().setUserAgentString(
                "Mozilla/5.0 (Linux; Android 14; Pixel 8) " +
                "AppleWebKit/537.36 (KHTML, like Gecko) " +
                "Chrome/125.0.0.0 Mobile Safari/537.36");

        // 构建对话框
        AlertDialog dialog = new AlertDialog.Builder(context)
                .setTitle("登录 B站")
                .setView(webView)
                .setNegativeButton("关闭", null)
                .show();

        // 监听页面加载完成，检测是否已登录
        webView.setWebViewClient(new WebViewClient() {
            @Override
            public void onPageFinished(WebView view, String url) {
                super.onPageFinished(view, url);

                // 如果 URL 跳转到 bilibili.com 主站，说明登录成功
                if (url.contains("www.bilibili.com")
                        && !url.contains("login")
                        && !url.contains("passport")) {
                    // 提取并保存 Cookie
                    saveCookies(context);
                    dialog.dismiss();
                    if (callback != null) {
                        callback.onLoginResult(true, "B站 登录成功");
                    }
                }
            }

            @Override
            public boolean shouldOverrideUrlLoading(
                    WebView view, WebResourceRequest request) {
                // 在 WebView 内部加载链接，不跳转到浏览器
                view.loadUrl(request.getUrl().toString());
                return true;
            }
        });

        // 加载 B站 登录页
        webView.loadUrl("https://passport.bilibili.com/login");
    }

    /*
     * saveCookies: 从 WebView 提取 Cookie 并保存到文件 + SharedPreferences
     */
    private static void saveCookies(Context context) {
        try {
            // 获取 bilibili.com 域下的所有 Cookie
            CookieManager cookieManager = CookieManager.getInstance();
            String cookies = cookieManager.getCookie(".bilibili.com");

            if (cookies == null || cookies.isEmpty()) {
                return;
            }

            // 保存到文件（yt-dlp 需要的 Netscape 格式）
            File cookieFile = new File(context.getFilesDir(), COOKIE_FILE_NAME);
            String netscapeCookies = convertToNetscapeFormat(cookies);
            FileOutputStream fos = new FileOutputStream(cookieFile);
            fos.write(netscapeCookies.getBytes(StandardCharsets.UTF_8));
            fos.close();

            // 保存登录状态
            SharedPreferences prefs = context
                    .getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE);
            prefs.edit()
                    .putBoolean(KEY_BILI_LOGGED_IN, true)
                    .putString("bilibili_cookies_raw", cookies)
                    .apply();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /*
     * convertToNetscapeFormat: 将 Cookie 字符串转换为 Netscape HTTP Cookie 文件格式
     * yt-dlp 使用 --cookies 参数时要求 Netscape 格式
     */
    private static String convertToNetscapeFormat(String rawCookies) {
        StringBuilder sb = new StringBuilder();
        // Netscape Cookie 文件头
        sb.append("# Netscape HTTP Cookie File\n");
        sb.append("# https://curl.se/rfc/cookie_spec.html\n");
        sb.append("# This file was generated by GrayVideoDL\n\n");

        // 逐条解析 Cookie
        String[] cookieEntries = rawCookies.split(";");
        for (String entry : cookieEntries) {
            entry = entry.trim();
            if (entry.isEmpty()) continue;

            String[] parts = entry.split("=", 2);
            if (parts.length == 2) {
                String name = parts[0].trim();
                String value = parts[1].trim();

                // Netscape 格式: domain flag path secure expiry name value
                // .bilibili.com  TRUE  /  FALSE  0  NAME  VALUE
                sb.append(".bilibili.com\t")
                  .append("TRUE\t")
                  .append("/\t")
                  .append("FALSE\t")
                  .append("0\t")
                  .append(name).append("\t")
                  .append(value).append("\n");
            }
        }

        return sb.toString();
    }

    /*
     * getCookieFile: 获取保存的 Cookie 文件路径
     * 供 HomeFragment 调用传递给 Python 桥接
     */
    public static String getCookieFilePath(Context context) {
        File cookieFile = new File(context.getFilesDir(), COOKIE_FILE_NAME);
        return cookieFile.exists() ? cookieFile.getAbsolutePath() : "";
    }

    /*
     * isLoggedIn: 检查是否已登录 B站
     */
    public static boolean isLoggedIn(Context context) {
        SharedPreferences prefs = context
                .getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE);
        return prefs.getBoolean(KEY_BILI_LOGGED_IN, false);
    }

    /*
     * getRawCookies: 获取保存的原始 Cookie 字符串
     * 以 "key1=value1; key2=value2" 格式返回
     */
    public static String getRawCookies(Context context) {
        SharedPreferences prefs = context
                .getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE);
        return prefs.getString("bilibili_raw_cookies", "");
    }

    /*
     * loadFromAssets: 从 assets/bilibili_cookies.txt 加载 Cookie
     * 解析 Netscape 格式的 Cookie 文件，提取 name=value 对，
     * 保存到 SharedPreferences 并标记为已登录。
     * 每次启动时调用，确保 Cookie 始终可用。
     */
    public static void loadFromAssets(Context context) {
        try {
            // 读取 assets 中的 Cookie 文件
            android.content.res.AssetManager am = context.getAssets();
            java.io.InputStream is = am.open("bilibili_cookies.txt");
            byte[] buffer = new byte[is.available()];
            is.read(buffer);
            is.close();
            String content = new String(buffer,
                    java.nio.charset.StandardCharsets.UTF_8);

            // 解析 Netscape 格式，提取 name=value 对
            StringBuilder rawCookies = new StringBuilder();
            String[] lines = content.split("\n");
            for (String line : lines) {
                line = line.trim();
                // 跳过注释行和空行
                if (line.isEmpty() || line.startsWith("#")) continue;

                // Netscape 格式: domain TAB flag TAB path TAB secure TAB expiry TAB name TAB value
                String[] parts = line.split("\t");
                if (parts.length >= 7) {
                    String name = parts[parts.length - 2].trim();
                    String value = parts[parts.length - 1].trim();
                    if (rawCookies.length() > 0) rawCookies.append("; ");
                    rawCookies.append(name).append("=").append(value);
                }
            }

            String cookies = rawCookies.toString();
            if (cookies.isEmpty()) return;

            // 保存到 SharedPreferences（使用 commit 确保同步写入）
            SharedPreferences prefs = context
                    .getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE);
            prefs.edit()
                    .putBoolean(KEY_BILI_LOGGED_IN, true)
                    .putString("bilibili_raw_cookies", cookies)
                    .commit();

            // 同时保存为 Netscape 文件
            File cookieFile = new File(context.getFilesDir(), COOKIE_FILE_NAME);
            java.io.FileOutputStream fos = new java.io.FileOutputStream(cookieFile);
            fos.write(content.getBytes(
                    java.nio.charset.StandardCharsets.UTF_8));
            fos.close();

        } catch (Exception e) {
            // assets 中没有 Cookie 文件或读取失败，忽略
        }
    }
}
